# [START django_app]
runtime: python37
env_variables:
  BUCKET_NAME: "gae-bizlead"

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: covidX/static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  secure: always
  script: auto
# TODO(codecakes): Remove later when staging/prod.
basic_scaling:
  max_instances: 1
# [END django_app]
