# [START django_app]
runtime: python38
env_variables:
  BUCKET_NAME: "gae-bizlead"
  SECRET_ID: "SECRET_KEY"
  DJANGO_SETTINGS_MODULE: "covidX.settings.base"
  WSGI_APPLICATION: "covidX.wsgi.application"
resources:
  memory_gb: 4
handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  secure: always
  script: auto
# TODO(codecakes): Remove later when staging/prod.
automatic_scaling:
  min_idle_instances: 1
  min_instances: 1
  max_instances: 1

# [END django_app]
