steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['./secrets.sh']
- name: 'index.docker.io/codecakes/buster_py'
  entrypoint: 'bash'
  args: ['./gen_static.sh']
  env:
    - 'SECRET_KEY=testsecret'

