steps:
- name: 'index.docker.io/codecakes/buster_py'
  entrypoint: 'bash'
  args: ['./gen_static.sh']
  env:
    - 'SECRET_KEY=testsecret'
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['./secrets.sh']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--verbosity=debug', '--stop-previous-version']
