apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: covidx-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: covidx
    spec:
      containers:
      - name: covidx-container
        image: covidx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
